config/routes.rb
Rails.application.routes.draw do
  resources :talks do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/talk.rb
class Talk < ApplicationRecord
  validates:content, presence: true
  validates:content, length: { in: 1..140 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
before_action:set_talk, only:[:show, :edit, :update, :destroy]
  def index
    @talks=Talk.all
  end

  def new
    if params[:back]
      @talk=Talk.new(talk_params)
    else
      @talk=Talk.new
    end
  end

  def confirm
    @talk=Talk.new(talk_params)
    @talk.valid?
  end

  def create
    @talk=Talk.new(talk_params)
    if @talk.save
       redirect_to talks_path, notice: "作成しました！"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @talk.update(talk_params)
      redirect_to talks_path, notice:"編集しました"
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @talk.destroy
    redirect_to talks_path, notice:"削除しました！"
  end

  private

  def talk_params
    params.require(:talk).permit(:content)
  end

  def set_talk
    @talk = Talk.find(params[:id])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/talks_helper.rb
module TalksHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_talks_path
    elsif action_name == 'edit'
      talk_path
    end
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweet_Clone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">  <!-- head内にこのタグ設定を追記する -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <ul>
        <li><a href="#">Twitter Clone</a></li>
        <li><a href="#">トップページ</a></li>
      </ul>
    </header>

    <%= yield %>

    <footer>
      <p> DIC Rails基礎課題</p>
    </footer>

  </body>
</html>

app/views/talks/_form.html.erb
<%= form_with(model: @talk, local: true, url: choose_new_or_edit) do |form| %>

<% if @talk.errors.any? %>
  <div id="error_explanation">
    <h2><%= @talk.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @talk.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="talk_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "一覧画面にもどる", talks_path %>

app/views/talks/confirm.html.erb
<h1>Confirmation</h1>
<h3>確認画面。以下の内容で、送信する。</h3>

<% if @talk.errors.any? %>
  <div id="error_explanation">
    <h2><%= @talk.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @talk.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @talk, url: talks_path, local:true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @talk.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model:@talk, url:new_talk_path, local:true, method:'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name:'back' %>
<% end %>

app/views/talks/edit.html.erb
<h1>Edit Tweet</h1>

<%= render 'form' %>

app/views/talks/index.html.erb
<div class="container">

  <h1> Tweet List </h1>

  <div id="new-blog-link">
    <%= link_to '新規ツイートを作成する', new_talk_path %>
  </div>

  <div class="row">
    <% @talks.each do |talk| %>
      <div class="col-xs-12 col-md-6 talk-panel">
        <h3><%= talk.content %></h3>
        <p><%= talk.created_at %></p>
        <div class="talk-links">
          <%= link_to '詳細', talk, class:'btn btn-default'%>
          <%= link_to '編集', edit_talk_path(talk), class: 'btn btn-default' %>
          <%= link_to '削除', talk, method: :delete, data:{confirm: '本当に削除して良いですか？'}, class:'btn btn-default' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/talks/index_bkup.html.erb
<div class="container">

  <header class="header">
    Bootstrap
    <span class="label label-default"> new </span>
  </header>

  <div class="alert alert-sucess" role="alert">
      alert class2
  </div>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target ="#gnavi">
          <span class="sr-only">Bootstrap</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" haref="#">Bootstrap</a>
      </div>
      <div id="gnavi" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="">top</a></li>
          <li><a href="">menu1</a></li>
          <li><a href="">menu2</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <article>
      <div class="contents">
          <ul class="row">
              <li class="col-md-6">contents1</li>
              <li class="col-md-6">contents2</li>
          </ul>
      </div>
      <div class="topic">
           <ul>
              <li>bootstrapを使ってレスポンシブデザインを実現しよう！</li>
              <li>やればできる！bootstrapを使ってみよう！</li>
              <li>怖くない！レスポンシブデザインができるようになればWebアプリケーションもワンランク上に！</li>
          </ul>
      </div>
  </article>
</div>

app/views/talks/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

app/views/talks/show.html.erb
<h1>Tweet Detail</h1>

<p>内容：<%= @talk.content %></p>
<%= link_to '戻る', :back %>